labNum = input("Enter the number of labs completed: ")
quizNum = input("Enter the number of quizzes completed: ")
assignment1 = input("Enter grade for Assignment 1: ") 
assignment2 = input("Enter grade for Assignment 2: ")
assignment3 = input("Enter grade for Assignment 3: ")
assignment4 = input("Enter grade for Assignment 4: ")
midterm1 = input("Enter grade for Midterm 1: ")
midterm2 = input("Enter grade for Midterm 2: ")
final = input("Enter grade for Final Exam: ")
prep = input("Enter grade for Midterms and Final Preparation: ")
finalGrade = ((assignment1 * 0.04) + (assignment2 * 0.04) + (assignment3 * 0.04) + (assignment4 * 0.04)) + mid1 + mid2 + fin + prep)
print("Your grade is: " + finalGrade)
